# Create ConfigMap postgres-secret for the postgres app
#https://adamtheautomator.com/postgres-to-kubernetes/#Deploying_PostgreSQL_to_Kubernetes_Manually
# Define default database name, user, and password
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret-servicio-puntos
  labels:
    app: postgres-servicio-puntos
data:
  POSTGRES_DB: crud
  POSTGRES_USER: pg
  POSTGRES_PASSWORD: pass
---
apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgresql-data-servicio-puntos # Sets PV's name
  labels:
    type: local # Sets PV's type to local
    app: postgres-servicio-puntos
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgressql-servicio-puntos" # Sets the volume's path
---
#kubectl get pvc , must show bound
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: postgresql-data-claim-servicio-puntos # Sets name of PV
  labels:
    app: postgres-servicio-puntos
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
---
apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres-servicio-puntos # Set the name of the deployment
spec:
  replicas: 1 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: postgres-servicio-puntos
  template:
    metadata:
      labels:
        app: postgres-servicio-puntos
    spec:
      containers:
        - name: postgres
          image: postgres:12.10 # Docker image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: postgres-secret-servicio-puntos # Using the ConfigMap postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql-servicio-puntos/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresql-data-claim-servicio-puntos
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-servicio-puntos
spec:
  selector:
    app: postgres-servicio-puntos
  ports:
    - port: 5432