apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-puntos
  labels:
    app: servicio-puntos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-puntos
  template:
    metadata:
      labels:
        app: servicio-puntos
    spec:
      containers:
      - name: servicio-puntos
        image: servicio-puntos:v0.0.3
        ports:
        - containerPort: 4000
        env:
        - name: DB_PATH
          value: "postgres://pg:pass@postgres-servicio-puntos:5432/crud"
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-puntos
spec:
  selector:
    app: servicio-puntos
  ports:
    - port: 4000